import type { AppData } from './types'

export const demoData: AppData = {
  graphs: [
    {
      id: 'graph-age-of-revolutions',
      title: 'Age of Revolutions',
      description: 'Unit/Bridge/Global study graph focused on recall of historical relationships.',
      createdAt: '2026-04-09T00:00:00Z',
      updatedAt: '2026-04-09T00:00:00Z',
      units: [
        { id: 'enlightenment', title: 'Enlightenment', order: 1 },
        { id: 'french-revolution', title: 'French Revolution', order: 2 },
        { id: 'napoleonic-era', title: 'Napoleonic Era', order: 3 },
        { id: 'congress-vienna', title: 'Congress of Vienna', order: 4 },
      ],
      cards: [
        { id: 'enlightenment-movement', title: 'Enlightenment', summary: 'Reason-based critique of tradition.', detail: 'Intellectual movement reshaping political legitimacy.', unitId: 'enlightenment', cardType: 'concept', dateLabel: 'c. 1685–1815' },
        { id: 'john-locke', title: 'John Locke', summary: 'Natural rights thinker.', detail: 'Argued government rests on consent and rights.', unitId: 'enlightenment', cardType: 'person', dateLabel: '1632–1704' },
        { id: 'montesquieu', title: 'Montesquieu', summary: 'Separation of powers theorist.', detail: 'Promoted checks on concentrated authority.', unitId: 'enlightenment', cardType: 'person', dateLabel: '1689–1755' },
        { id: 'rousseau', title: 'Rousseau', summary: 'Popular sovereignty advocate.', detail: 'Linked political authority to the general will.', unitId: 'enlightenment', cardType: 'person', dateLabel: '1712–1778' },
        { id: 'social-contract', title: 'Social Contract', summary: 'Political legitimacy from agreement.', detail: 'Framework for consent-based governance.', unitId: 'enlightenment', cardType: 'concept' },
        { id: 'separation-powers', title: 'Separation of Powers', summary: 'Institutional division of authority.', detail: 'Legislative, executive, judicial balancing.', unitId: 'enlightenment', cardType: 'concept' },
        { id: 'popular-sovereignty', title: 'Popular Sovereignty', summary: 'Authority originates in the people.', detail: 'Used to challenge hereditary rule.', unitId: 'enlightenment', cardType: 'concept' },

        { id: 'ancien-regime', title: 'Ancien Régime', summary: 'Pre-1789 French order.', detail: 'Estate privilege and fiscal strain.', unitId: 'french-revolution', cardType: 'institution' },
        { id: 'estates-general', title: 'Estates-General', summary: 'Representative body convened in crisis.', detail: 'Summoned in 1789 after long dormancy.', unitId: 'french-revolution', cardType: 'institution', dateLabel: '1789' },
        { id: 'national-assembly', title: 'National Assembly', summary: 'Revolutionary legislative body.', detail: 'Third Estate redefined sovereignty.', unitId: 'french-revolution', cardType: 'institution', dateLabel: '1789' },
        { id: 'tennis-court-oath', title: 'Tennis Court Oath', summary: 'Commitment to constitution-making.', detail: 'Symbolic refusal to disperse.', unitId: 'french-revolution', cardType: 'event', dateLabel: 'June 20, 1789' },
        { id: 'declaration-rights-man', title: 'Declaration of the Rights of Man and Citizen', summary: 'Rights-based revolutionary text.', detail: 'Liberty and equality principles.', unitId: 'french-revolution', cardType: 'text', dateLabel: '1789' },
        { id: 'french-revolution-core', title: 'French Revolution', summary: 'Transformation of French state and society.', detail: 'From constitutional reform to radicalization.', unitId: 'french-revolution', cardType: 'event', dateLabel: '1789–1799' },
        { id: 'reign-terror', title: 'Reign of Terror', summary: 'Radical emergency politics.', detail: 'Mass executions under revolutionary pressure.', unitId: 'french-revolution', cardType: 'event', dateLabel: '1793–1794' },
        { id: 'robespierre', title: 'Robespierre', summary: 'Jacobin leader in radical phase.', detail: 'Associated with virtue and terror politics.', unitId: 'french-revolution', cardType: 'person', dateLabel: '1758–1794' },

        { id: 'napoleon', title: 'Napoleon Bonaparte', summary: 'Military ruler and reformer.', detail: 'Consolidated gains while centralizing authority.', unitId: 'napoleonic-era', cardType: 'person', dateLabel: '1769–1821' },
        { id: 'consulate', title: 'Consulate', summary: 'Post-revolution executive regime.', detail: 'Stabilization phase before empire.', unitId: 'napoleonic-era', cardType: 'institution', dateLabel: '1799–1804' },
        { id: 'napoleonic-code', title: 'Napoleonic Code', summary: 'Civil-law codification.', detail: 'Standardized legal rights and property norms.', unitId: 'napoleonic-era', cardType: 'text', dateLabel: '1804' },
        { id: 'first-french-empire', title: 'First French Empire', summary: 'Imperial expansion under Napoleon.', detail: 'Military dominance across Europe.', unitId: 'napoleonic-era', cardType: 'institution', dateLabel: '1804–1814/15' },
        { id: 'meritocracy', title: 'Meritocracy', summary: 'Advancement by ability and service.', detail: 'Revolutionary and Napoleonic administrative logic.', unitId: 'napoleonic-era', cardType: 'concept' },
        { id: 'continental-warfare', title: 'Continental Warfare', summary: 'Large-scale coalition conflict.', detail: 'Wars transformed Europe-wide politics.', unitId: 'napoleonic-era', cardType: 'event', dateLabel: '1792–1815' },

        { id: 'congress-vienna-core', title: 'Congress of Vienna', summary: 'Settlement after Napoleonic wars.', detail: 'Redrew borders and sought long-term stability.', unitId: 'congress-vienna', cardType: 'event', dateLabel: '1814–1815' },
        { id: 'metternich', title: 'Klemens von Metternich', summary: 'Austrian statesman of restoration order.', detail: 'Architect of conservative diplomacy.', unitId: 'congress-vienna', cardType: 'person', dateLabel: '1773–1859' },
        { id: 'legitimacy', title: 'Legitimacy', summary: 'Restore lawful dynastic authority.', detail: 'Counterweight to revolutionary upheaval.', unitId: 'congress-vienna', cardType: 'concept' },
        { id: 'balance-power', title: 'Balance of Power', summary: 'Prevent hegemonic domination.', detail: 'Distribution of strength across states.', unitId: 'congress-vienna', cardType: 'concept' },
        { id: 'concert-europe', title: 'Concert of Europe', summary: 'Great-power consultation mechanism.', detail: 'Post-1815 framework for crisis management.', unitId: 'congress-vienna', cardType: 'institution', dateLabel: '1815 onward' },
        { id: 'restoration', title: 'Restoration', summary: 'Return of pre-revolution dynasties.', detail: 'Attempt to rebuild conservative order.', unitId: 'congress-vienna', cardType: 'concept' },
      ],
      edges: [
        { id: 'e1', from: 'enlightenment-movement', to: 'john-locke', cue: 'major thinker', reason: 'Locke is a foundational Enlightenment political thinker.', slot: 'A', relationType: 'includes', importance: 'core', scope: 'intra-unit' },
        { id: 'e2', from: 'enlightenment-movement', to: 'montesquieu', cue: 'major thinker', reason: 'Montesquieu shapes constitutional thought.', slot: 'B', relationType: 'includes', importance: 'core', scope: 'intra-unit' },
        { id: 'e3', from: 'enlightenment-movement', to: 'rousseau', cue: 'major thinker', reason: 'Rousseau radicalizes sovereignty concepts.', slot: 'C', relationType: 'includes', importance: 'core', scope: 'intra-unit' },
        { id: 'e4', from: 'montesquieu', to: 'separation-powers', cue: 'key idea', reason: 'Montesquieu formulates separation-of-powers logic.', slot: 'A', relationType: 'articulates', importance: 'core', scope: 'intra-unit' },
        { id: 'e5', from: 'rousseau', to: 'popular-sovereignty', cue: 'key idea', reason: 'Rousseau ties authority to the people.', slot: 'A', relationType: 'articulates', importance: 'core', scope: 'intra-unit' },
        { id: 'e6', from: 'john-locke', to: 'social-contract', cue: 'consent', reason: 'Locke presents consent-based government principles.', slot: 'A', relationType: 'articulates', importance: 'secondary', scope: 'intra-unit' },
        { id: 'e7', from: 'ancien-regime', to: 'estates-general', cue: 'crisis response', reason: 'Fiscal crisis pushes monarchy to summon the Estates-General.', slot: 'A', relationType: 'triggers', importance: 'core', scope: 'intra-unit' },
        { id: 'e8', from: 'estates-general', to: 'national-assembly', cue: 'representation shift', reason: 'Third Estate transforms representation into national sovereignty.', slot: 'A', relationType: 'transforms-into', importance: 'core', scope: 'intra-unit' },
        { id: 'e9', from: 'national-assembly', to: 'tennis-court-oath', cue: 'commitment', reason: 'Assembly members pledge constitutional persistence.', slot: 'A', relationType: 'commits-to', importance: 'secondary', scope: 'intra-unit' },
        { id: 'e10', from: 'national-assembly', to: 'declaration-rights-man', cue: 'rights text', reason: 'Assembly authors rights declaration.', slot: 'B', relationType: 'produces', importance: 'core', scope: 'intra-unit' },
        { id: 'e11', from: 'french-revolution-core', to: 'reign-terror', cue: 'radical phase', reason: 'War and factional conflict produce the Terror.', slot: 'A', relationType: 'intensifies-into', importance: 'core', scope: 'intra-unit' },
        { id: 'e12', from: 'reign-terror', to: 'robespierre', cue: 'leader', reason: 'Robespierre symbolizes Jacobin emergency politics.', slot: 'A', relationType: 'associated-with', importance: 'secondary', scope: 'intra-unit' },
        { id: 'e13', from: 'napoleon', to: 'consulate', cue: 'regime base', reason: 'Napoleon first rules through the Consulate.', slot: 'A', relationType: 'leads', importance: 'core', scope: 'intra-unit' },
        { id: 'e14', from: 'napoleon', to: 'first-french-empire', cue: 'imperial phase', reason: 'Napoleon crowns himself emperor and expands authority.', slot: 'B', relationType: 'establishes', importance: 'core', scope: 'intra-unit' },
        { id: 'e15', from: 'consulate', to: 'napoleonic-code', cue: 'legal reform', reason: 'Consular period launches codification reforms.', slot: 'A', relationType: 'produces', importance: 'core', scope: 'intra-unit' },
        { id: 'e16', from: 'napoleonic-code', to: 'meritocracy', cue: 'careers open', reason: 'Code-era institutions support talent-based advancement norms.', slot: 'A', relationType: 'supports', importance: 'secondary', scope: 'intra-unit' },
        { id: 'e17', from: 'first-french-empire', to: 'continental-warfare', cue: 'coalition wars', reason: 'Imperial expansion drives repeated coalition conflict.', slot: 'A', relationType: 'drives', importance: 'core', scope: 'intra-unit' },
        { id: 'e18', from: 'congress-vienna-core', to: 'metternich', cue: 'chief diplomat', reason: 'Metternich is central in Vienna diplomacy.', slot: 'A', relationType: 'led-by', importance: 'core', scope: 'intra-unit' },
        { id: 'e19', from: 'congress-vienna-core', to: 'legitimacy', cue: 'principle', reason: 'Vienna promotes dynastic legitimacy.', slot: 'B', relationType: 'endorses', importance: 'core', scope: 'intra-unit' },
        { id: 'e20', from: 'congress-vienna-core', to: 'balance-power', cue: 'principle', reason: 'Settlement seeks strategic equilibrium.', slot: 'C', relationType: 'endorses', importance: 'core', scope: 'intra-unit' },
        { id: 'e21', from: 'congress-vienna-core', to: 'concert-europe', cue: 'mechanism', reason: 'Vienna system evolves into concert diplomacy.', slot: 'D', relationType: 'institutionalizes', importance: 'core', scope: 'intra-unit' },
        { id: 'e22', from: 'legitimacy', to: 'restoration', cue: 'application', reason: 'Legitimacy principle justifies restoration policies.', slot: 'A', relationType: 'supports', importance: 'secondary', scope: 'intra-unit' },

        { id: 'e23', from: 'popular-sovereignty', to: 'french-revolution-core', cue: 'ideological bridge', reason: 'Popular sovereignty informs revolutionary claims of representation.', slot: 'A', relationType: 'influences', importance: 'core', scope: 'cross-unit' },
        { id: 'e24', from: 'separation-powers', to: 'declaration-rights-man', cue: 'constitutional language', reason: 'Separation-of-powers thought shapes rights-era constitutional design.', slot: 'A', relationType: 'influences', importance: 'secondary', scope: 'cross-unit' },
        { id: 'e25', from: 'social-contract', to: 'national-assembly', cue: 'consent logic', reason: 'Contract theory strengthens representative legitimacy arguments.', slot: 'A', relationType: 'legitimizes', importance: 'secondary', scope: 'cross-unit' },
        { id: 'e26', from: 'reign-terror', to: 'napoleon', cue: 'stability demand', reason: 'Terror-era instability increases demand for order and authority.', slot: 'B', relationType: 'opens-path-for', importance: 'core', scope: 'cross-unit' },
        { id: 'e27', from: 'declaration-rights-man', to: 'napoleonic-code', cue: 'rights to law', reason: 'Rights discourse informs later codified legal reform debates.', slot: 'A', relationType: 'prefigures', importance: 'secondary', scope: 'cross-unit' },
        { id: 'e28', from: 'continental-warfare', to: 'congress-vienna-core', cue: 'settlement need', reason: 'Prolonged war compels postwar diplomatic settlement.', slot: 'A', relationType: 'necessitates', importance: 'core', scope: 'cross-unit' },
        { id: 'e29', from: 'first-french-empire', to: 'balance-power', cue: 'anti-hegemony', reason: 'Fear of French hegemony sharpens balance-of-power doctrine.', slot: 'B', relationType: 'provokes', importance: 'core', scope: 'cross-unit' },
        { id: 'e30', from: 'napoleon', to: 'restoration', cue: 'reaction', reason: 'Napoleonic disruption triggers conservative restoration efforts.', slot: 'C', relationType: 'provokes-reaction', importance: 'core', scope: 'cross-unit' },
      ],
      progress: [],
    },
  ],
}
